### ISSUE TITLE
Error in Firefox Browsers

### ISSUE THREAD

**Issue by DamianRivas** [chidimo/react-dnd#4]
I get the following error in Firefox:
```
NoModificationAllowedError: Modifications are not allowed for this document
```

This happens when this line is run in `handleDrop`
```js
e.dataTransfer.clearData();
```

This is what MDN has to say about it
> This method can only be used in the handler for the dragstart event, because that's the only time the drag operation's data store is writeable.

The tutorial does not explain the purpose of `clearData()` here. Is it necessary in the first place?

https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/clearData

![image](https://user-images.githubusercontent.com/10257813/77504977-14c94e00-6e1f-11ea-9e4f-04ae1012601f.png)

**Comment by chidimo** [comment]
Thank you for catching this @DamianRivas.

It was an attempt to remove the dragged files from memory, but I realize now that by dropping the files I already removed it from memory and I can start afresh with a new `dataTransfer.files` for every drag operation.

I hadn't noticed the error before until now. I have the same component in one of my production apps and it seems to work fine. I noticed though that the error is thrown without crashing the page, with the effect that the lines

```javascript
dispatch({ type: 'SET_DROP_DEPTH', dropDepth: 0 });
dispatch({ type: 'SET_IN_DROP_ZONE', inDropZone: false });
```

are not executed. So the drop zone does not return to its initial styling state.

I've removed the method call.
