### ISSUE TITLE
handleDragLeave not working properly

### ISSUE THREAD

**Issue by DamianRivas** [chidimo/react-dnd#5]
This part of `handleDragLeave` doesn't work properly for me in any browser in Windows 10.
```js
if (data.dropDepth > 0) return;
dispatch({ type: "SET_IN_DROP_ZONE", inDropZone: false });
```

`inDropZone` is not updated although `dropDepth` is 0. I think this is because of how React handles changes in state. It does it asynchronously so `dispatch({ type: "SET_DROP_DEPTH", dropDepth: data.dropDepth - 1 })` is simply added to the event loop. Therefore, `dropDepth` is not 0 by the time it reaches the `if` statement.

![image](https://user-images.githubusercontent.com/10257813/77505585-d2a10c00-6e20-11ea-9187-2d2f3d5c9945.png)

**Comment by DamianRivas** [comment]
I forgot to mention that simply changing the `if` statement to `if (data.dropDepth > 1)` solves the issue. If we are about to to decrement `dropDepth` and it's currently 1, then we know it's going to be `0`

**Comment by chidimo** [comment]
I haven't tested this in a windows environment. But thanks for noting this. Even though the state update happens asynchronously, I think it should happen fast enough.

Your reason for making a comparison with `1` makes sense.
